version: '3'

services:
  #MYSQL
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql-container 
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_DATABASE: message
      MYSQL_PASSWORD: password
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf